### ISSUE TITLE
window.crypto.subtle being undefined on chrome

### ISSUE THREAD

**Issue by github0013** [encrypted-dev/userbase#125]
- Version 80.0.3987.132 (Official Build) (64-bit)
- Darwin mbp.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64

<img width="431" alt="Ugliest_To-Do" src="https://user-images.githubusercontent.com/809378/76593901-eacc7d80-653a-11ea-874f-5b4ff033de09.png">

and I get `ServiceUnavailable`.

Same code works on Firefox Version 73.0.1.

**Comment by dvassallo** [comment]
Hi. This is likely because you’re loading your site from an http endpoint.
Chrome only allows crypto to load on http when using localhost. Otherwise,
it has to be https.

**Comment by github0013** [comment]
https://stackoverflow.com/questions/46468104/how-to-use-subtlecrypto-in-chrome-window-crypto-subtle-is-undefined

I just found the same answer..
