### ISSUE TITLE
Excessive Client Package Size

### ISSUE THREAD

**Issue by rhucle** [encrypted-dev/userbase#133]
Userbase looks promising and definitely satisfies a need in front-end development.

However, I noticed the client library is massive: ~70K gzipped. Much of which comes from `@babel/runtime-corejs3`.

In general, client libraries don't ship polyfills. Instead, they note browser support in the README and let consumers polyfill as needed. Not reason every consumer should have to bear the burden of `@babel/runtime-corejs3`.

Likewise with `axios`. It's not much compared to `@babel/runtime-corejs3`, but 4K isn't nothing. And it's certainly not carrying its own weight given it's used only in `api/auth.js`. Consider using `fetch` directly and—again—letting the consumer polyfill as needed. 

Perhaps all of this known and temporary. If so, please disregard.

**Comment by dvassallo** [comment]
Thank you, and this is absolutely something we’ll prioritize soon.

**Comment by j-berman** [comment]
Done!

gzipped size now down to ~40K! :)

Browser compatibility list provided [here](https://github.com/encrypted-dev/userbase/blob/cb5842fd9124d2724325b408a3775fb49d81d22c/src/userbase-js/README.md#browser-compatibility).

Thank you for the suggestions!
