### ISSUE TITLE
User logout after trying to change password

### ISSUE THREAD

**Issue by marcomelilli** [encrypted-dev/userbase#147]
When I try to change password with 
```
userbase.updateUser({
  currentPassword: 'example-password',
  newPassword: 'example-new-password'
})
```
If I enter the right currentPassword, it works well and It changes the password with the new one.

But if I enter the wrong password i receive this error "CurrentPasswordIncorrect", and it seems that it terminates the current session. If I retry to do another request I receive the error: UserNotSignedIn and I need to login again.

**Comment by dvassallo** [comment]
Hi Marco — That seems like unintended behavior. We're going to look at it and report back asap.

**Comment by j-berman** [comment]
Hey Marco, I'm unable to to reproduce this -- I can retry after receiving the error. Are you still able to reproduce this in this exact way?

**Comment by marcomelilli** [comment]
hi @j-berman , I just retried and I discovered that's was my fault 😅
In my app I was handling all 401 responses with a logout, I didn't expect this status code in this case.

I'm closing the issue, sorry and thanks for the support
