### ISSUE TITLE
It would be nice if `updateUser` returned the updated user

### ISSUE THREAD

**Issue by raae** [encrypted-dev/userbase#172]
So one does not have to manage updating the user data in the client code. It could also be changed on another client and would be nice to get the current user from the server whenever doing change,

**Comment by j-berman** [comment]
How does this proposal sound?

- `updateUser()` will return the following object:
  - user
    - username
    - userId
    - authToken
    - creationDate
    - email (only if set)
    - profile (only if set)
    - protectedProfile (only if set)
    - paymentsMode (only if set)
    - subscriptionStatus (only if set)
    - trialExpirationDate (only if set)
    - cancelSubscriptionAt (only if set)
- [init()](https://userbase.com/docs/sdk/init/) will accept a callback function as a parameter called `updateUserHandler`.
- When a user is updated via [updateUser()](https://userbase.com/docs/sdk/update-user/) in the SDK, or [Update User](https://userbase.com/docs/api/update-user/) in the Admin API, the callback function is invoked with the object above.

**Comment by raae** [comment]
I do not know how I have missed the updateUserHandler, but i have.

Thanks 👍

**Comment by raae** [comment]
I must learn to read, not skim.

Opening again and will have a closer look an get back to you with a thoughtful comment.

**Comment by raae** [comment]
Yes, this sounds good and I guess more inline with how databases work.

**Comment by j-berman** [comment]
Deployed in userbase-js v2.1.0 as well!
