### ISSUE TITLE
A couple of bugs are detected by SonarCloud that should by fixed IMHO

### ISSUE THREAD

**Issue by agigleux** [encrypted-dev/userbase#174]
Hello,

I scanned your project with [SonarCloud](https://sonarcloud.io/) and I realized there are 2 categories of bugs detected that you should look at:
* Function calls should not pass extra arguments: there are currently 5 occurrences of this issue. While it's not hurting today, it's misleading to call a function with extra parameters if they are at the end not used - https://sonarcloud.io/project/issues?id=agigleux_userbase&languages=js&resolved=false&rules=javascript%3AS930&types=BUG
* Conditionally executed blocks should be reachable: https://sonarcloud.io/project/issues?id=agigleux_userbase&languages=js&open=AXN7IW3hP4fqw99sf4wU&resolved=false&rules=javascript%3AS2583&types=BUG

The problem is located on src/userbase-server/app.js

![image](https://user-images.githubusercontent.com/1057037/88291379-6e238a00-ccf8-11ea-8e25-c6ed71631425.png)

If `!app` is `true`, it means `app` is undefined so `app['app-id']` is also undefined and will fail at runtime.

Regards
Alex

**Comment by j-berman** [comment]
Thank you for this! Will fix. Useful tool.

**Comment by j-berman** [comment]
Done! Thanks again, Alex.
