### ISSUE TITLE
ServiceUnavailable: Service unavailable.

### ISSUE THREAD

**Issue by rulan** [encrypted-dev/userbase#430]
Not able to make use of the api, not able to login. Getting ServiceUnavailable: Service unavailable. error

**Comment by j-berman** [comment]
Have you been able to use Userbase before and it just now stopped working for you? Or is this your first time trying to use Userbase?

**Comment by rulan** [comment]
Userbase is now working properly, the issue lasted about 1 hour, I was not able to find the culprit. Might have been a general hiccup.
