### ISSUE TITLE
Choose a more searchable name

### ISSUE THREAD

**Issue by prabaker** [encrypted-dev/userbase#53]
This might be a shot in the dark, but I have had a hard time searching for userbase as a project name.  It gives many, many unrelated results on google 😉 

So I don't know whether you would consider changing to a less generic project name, but that would help people trying to do research or find docs quickly.

**Comment by mastrolinux** [comment]
As soon as the project will be more and more popular it will automatically ranked better in the search results. I am going to add some more tags in the project description.

Thank you for your feedback.
