### ISSUE TITLE
Please document what exact AWS resources are being used

### ISSUE THREAD

**Issue by mariusa** [encrypted-dev/userbase#90]
Hi,

Please list in README what exact AWS resources are being used and what for.
This is also useful to get an estimate of AWS billing.

Thanks

**Comment by rhino88** [comment]
@mariusa this can be found at the bottom of the FAQ section here: https://userbase.com/docs/faq/

> What services does Userbase depend on?
Userbase runs entirely on Amazon Web Services, in the us-east-1 region. The availability of the Userbase service depends on Amazon EC2, Amazon S3, and Amazon DynamoDB.
